### ISSUE TITLE
Starting Governance twice

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/plutus-use-cases#121]
It's possible to start Governance twice via endpoint with same parameters. Currently, it can lead to situation, when script would have more than one NFT token at its address, which will break transaction validation with current validator.

Corresponding test added to test suite.

**Comment by zygomeb** [comment]
By assumption only one NFT can exist that the governance script is parameterized by, therefore I see no reason to limit the amount of times a governance can be started (and after all, a malicious entity would be able to change it anyway).

**Comment by mikekeke** [comment]
Test removed.
