### ISSUE TITLE
Withdraw doesn't validate

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/plutus-use-cases#123]
Simple withdraw in tests fails with
```Contract instance stopped with error: "WalletError (ValidationError (ScriptFailure (EvaluationError [])))"```

**Comment by zygomeb** [comment]
I know what needs to be fixed, fails as expected. Can fix once I fix my current driver, but if you want to tackle it, which I would say is a good idea, you've been buried in these tests all this time :P You need to fix the think I commented with 'may need to fix this' -- by checking that a negative amount of xGOV is being minted instead (and equal to the sum provided)

**Comment by mikekeke** [comment]
I'll take this issue next then

**Comment by mikekeke** [comment]
Working branch for issue: `issues-123-withdraw`

**Comment by zygomeb** [comment]
Fixed on `governance-decentralised`
