### ISSUE TITLE
NFT: write basic test coverage to match previous nft smart contract testing 

### ISSUE THREAD

**Issue by cstml** [mlabs-haskell/plutus-use-cases#167]
After the re-write of the NFT smart contract we don't have any test suite for the new NFT smart contract. Re-implement the `legacy` tests in the new NFT contract. 

Depending on: #156  

Tasks:
- [x] Create basic test for 100% coverage
- [x] Create QuickCheck Tests

**Comment by zygomeb** [comment]
Assigned Tomasz to this issue
