### ISSUE TITLE
Update to new version of Plutus

### ISSUE THREAD

**Issue by anton-k** [mlabs-haskell/plutus-use-cases#23]
We are month behind the plutus team. So it's better to update
stack and nix build on the most recent plutus commit that works.

**Comment by mikekeke** [comment]
Here is PR with update: #80

**Comment by mikekeke** [comment]
PR #80 merged.
`Plutus` updated to commit `926a49d16439b693648b68b7e6eb7877a5e622e4` which is one of Jul 15 2021 commits.
