### ISSUE TITLE
Add documentation for the proposed use cases

### ISSUE THREAD

**Issue by cstml** [mlabs-haskell/plutus-use-cases#30]
The requirements for the documentation are as follows:
 - must be written as simple `.md` files,
 - must include the information described in the following documents: 
   - [IOHK Project Delivery Status Report](https://drive.google.com/file/d/1984k7_LDB6P6Kl0jfgu26628zxiJr9Bb/view?usp=sharing), 
   - [IOHK Partners Phase 1 Guidance](https://drive.google.com/file/d/1FxdjMeDFoF-PdC_zbav5ZJ5NOVDrnuti/view?usp=sharing).
  - must be finalised prior to _Phase1 Hard-Stop_ (2021.06.30) as described by the previous documents.

Note: *2021.06.23 updated broken links to GDrive*

**Comment by stackBlock** [comment]
I can help adding documentation - What exactly needs to be documented? 
I have looked at the reports and they seem to be guidelines on when and how to document but I am not sure what needs to be documented. Please let me know what daps or applications need documentation - or whatever I need to learn in order to write the documentation. 

Thanks,
Anthony

**Comment by cstml** [comment]
> I can help adding documentation - What exactly needs to be documented?
> I have looked at the reports and they seem to be guidelines on when and how to document but I am not sure what needs to be documented. Please let me know what daps or applications need documentation - or whatever I need to learn in order to write the documentation.
> 
> Thanks,
> Anthony

Cheers @stackBlock, that would be great. 
I will spend a couple of hours this morning pulling together an initial structure and hopefully that will make it easier to contribute. There will be a few things, but to name a few: 
- the build/installation, 
- the endpoints for each use-case  
- some examples. 

I will pull a bit more information out of the documents and include them in the structure.

**Comment by cstml** [comment]
As per update :point_up:, I have opened [PR #34 ](https://github.com/mlabs-haskell/plutus-use-cases/pull/34) where the conversation on this issue will be moved.
