### ISSUE TITLE
NFT: Fund collecting script

### ISSUE THREAD

**Issue by nrutledge** [mlabs-haskell/plutus-use-cases#350]
Maks mentioned that a script where market fees will go to needs to be created. I've added this issue as a reminder.

If this is irrelevant or captured in another issue, feel free to delete.

**Comment by zygomeb** [comment]
The script must have as parameter a list of pubkeyhashes that can unlock it 
that's about it for the simplest verstion -- version 2 would be to require a multisign majority from this list
