### ISSUE TITLE
standards - language pragma

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/plutus-use-cases#39]
the standards.md document describes a set of extensions that should be enabled by default in the package.yaml/cabal file, the rest should be enabled in the files that use them only.

please enforce this across the project.

**Comment by cstml** [comment]
Was looking at integrating these into the `mlabs-plutus-use-cases.cabal` and saw this:
> The following pragmata MUST be enabled at project level (that is, in **package.yaml**):

#24, #42 and some other tickets talk about using the `.cabal` file and a `nix` based workflow, and dropping the Stack based build. Should we modify the **Standards.md** to reflect this by changing `package.yaml` to `package.cabal` ?

**Comment by Benjmhart** [comment]
@cstml - stack.yaml will not be necessary once we have a working nix build.  

however there are probably some big refactors to the cabal file that are quite worthwhile once it isn't just generated code.
