### ISSUE TITLE
standards - record-dot-preprocessor

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/plutus-use-cases#40]
the standards document discourages lenses and accessor functions in favor of record dot preprocessor and record update syntax `record { alteredField = newValue}`,   please refactor any lenses used for getting/setting to record dot syntax across the project and enable the plugin if it is not already in use.

prisms and lenses used for other purposes are ok.

**Comment by jozanek** [comment]
Closed by #60
