### ISSUE TITLE
replace stack build with a nix build derivation using haskell.nix

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/plutus-use-cases#41]
we should be able to set up a derivation to build our binaries using iohk's haskell.nix

this should also make it easier to stay in lock-step with `plutus` as we will have fewer dependency mismatches.

acceptance criteria
- [x] running `nix build` will result in a successful build of our binaries.

additional:
- [x] our nix-shell should be derived from the environment that our default.nix (nix build) creates, along with extra tooling.  right now it is fully independant.

**Comment by cstml** [comment]
Additional specifications: 
- `nix-build` that runs without tests, haddock, etc. - maybe only typecheck

**Comment by cstml** [comment]
Additional specification:
- add documentation to `Readme`
