### ISSUE TITLE
document how to run ghci in the nix-shell

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/plutus-use-cases#42]
currently we have an issue with `cabal repl` where the plutus compiler plugin breaks the repl by default _when loading the library without an executable_

however, `cabal v2-repl lendex-demo` does work in the nix-shell

we should document the correct way to load a repl for each binary + test suite.

we should also correct a number of errors that pop up when trying to run `cabal v2-repl` or `stack repl` - in particular, this seems to deal with extensions that are applied to the executable but not the library (look at output when the repl initiates)

**Comment by cstml** [comment]
@Benjmhart have added `cabal repl` instructions to the Lendex documentation.

**Comment by Benjmhart** [comment]
@cstml this work is merged? if so we can close.
