### ISSUE TITLE
Lendex - transform SetUserReserveAsCollateral into two seperate endpoints

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/plutus-use-cases#70]
SetUserReserve is following some Ethereum design on Aave that makes it a bit strange and harder to test.

in short, there's boolean flag that completely changes the behavior.

let's make a change so that this is two endpoints.    `AddCollateral` and `RemoveCollateral`

I will update the spec this week.

**Comment by Benjmhart** [comment]
these have been added to the draft spec on this PR: https://github.com/mlabs-haskell/plutus-use-cases/pull/68

**Comment by mikekeke** [comment]
Related PR #90 merged to `main`
