### ISSUE TITLE
Lendex.QueryCurrentBalance

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/plutus-use-cases#75]
- [x] returns the user's funds currently locked in the current lendex, 
- [x] including both underlying tokens 
- [x]  aTokens of multiple kinds.
- [x] returns the user's current borrow amount 
- [x]  advances interest.  (see note)

**Comment by cstml** [comment]
Note: Interest is not advanced through a new Transaction as this would incur fees.
